version: '3.8'

services:
  # ============================================================
  # ZooKeeper
  # ============================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: 'CLIENT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'CLIENT://localhost:9092,INTERNAL://kafka1:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9093  # Укажите имя вашего контейнера Kafka
      # Если у Kafka есть авторизация (SASL), добавьте:
      # KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
    depends_on:
      - kafka1
  #=====================
  # Order service and DB
  # ============================================================
  order_db:
    container_name: order_db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ORDER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ORDER}
      POSTGRES_DB: ${POSTGRES_DB_ORDER}
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_ORDER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  order_app:
    container_name: order_app
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
      - ./src:/app/src    
      - ./CMakeLists.txt:/app/CMakeLists.txt
    ports:
      - '8181:8181'
    environment:
      DB_FULL_CONNECTION_STRING_ORDER: "host=${DB_HOST_ORDER} port=${DB_PORT_ORDER} dbname=${POSTGRES_DB_ORDER} user=${POSTGRES_USER_ORDER} password=${POSTGRES_PASSWORD_ORDER} sslmode=disable"
    depends_on:
      order_db:
        condition: service_healthy
    restart: unless-stopped

  # ============================================================
  # Payment service and DB
  # ============================================================
  payment_app:
    container_name: payment_app
    build: 
      context: ../PayMentService
      dockerfile: Dockerfile
    ports:
      - '8282:8282'
    environment:
      DB_FULL_CONNECTION_STRING_PAYMENT: "host=${DB_HOST_PAYMENT} port=${DB_PORT_PAYMENT} dbname=${POSTGRES_DB_PAYMENT} user=${POSTGRES_USER_PAYMENT} password=${POSTGRES_PASSWORD_PAYMENT} sslmode=disable"
    depends_on:
      payment_db:
        condition: service_healthy
    restart: unless-stopped

  payment_db:
    container_name: payment_db
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PAYMENT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PAYMENT}
      POSTGRES_DB: ${POSTGRES_DB_PAYMENT}
    volumes:
      - payment_db_data:/var/lib/postgresql/data
      - ../PayMentService/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_PAYMENT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  notification_app:
    container_name: notification_app
    build: 
      context: ../NotificationService
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      KAFKA_BROKERS: kafka:29092
    depends_on:
      kafka1:
        condition: service_started
    restart: unless-stopped

volumes:
  order_db_data:
  payment_db_data: